version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: shop_stripe_development
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d shop_stripe_development"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: bundle exec rails s -b '0.0.0.0'
    volumes:
      - '.:/shop_stripe'
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
