default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: user
  password: password

development:
  <<: *default
  database: shop_stripe_development

test:
  <<: *default
  database: shop_stripe_test

production:
  <<: *default
  database: shop_stripe_production
  username: shop_stripe
  password: <%= ENV['SHOP_STRIPE_DATABASE_PASSWORD'] %>
